In [119]:
import plotly.offline as py
import plotly.graph_objs as go
import pandas as pd
import math

py.init_notebook_mode()

In [120]:
data = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv")

In [121]:
df_2007 = data[data['year']==2007]

In [122]:
df_2007 = df_2007.sort(['continent', 'country'])

In [123]:
slope = 2.666051223553066e-05

In [124]:
hover_text = []
bubble_size = []

for index, row in df_2007.iterrows():
    hover_text.append('Country: {country}<br> Life Expectancy: {lifeExp}<br>GDP per capita: {gdp}'
               '<br>Population: {pop}<br>Year: {year}'.format(country=row['country'], 
                                                              lifeExp=row['lifeExp'], 
                                                              gdp=row['gdpPercap'], 
                                                              pop=row['pop'],
                                                              year=row['year']))
    bubble_size.append(math.sqrt(row['pop']*slope))

In [125]:
df_2007['text'] = hover_text
df_2007['size'] = bubble_size

In [126]:
df_2007.head()

,country,year,pop,continent,lifeExp,gdpPercap,text,size
35,Algeria,2007,33333216,Africa,72.301,6223.367465,Country: Algeria<br> Life Expectancy: 72.301<b...,29.810747
47,Angola,2007,12420476,Africa,42.731,4797.231267,Country: Angola<br> Life Expectancy: 42.731<br...,18.197150
131,Benin,2007,8078314,Africa,56.728,1441.284873,Country: Benin<br> Life Expectancy: 56.728<br>...,14.675558
167,Botswana,2007,1639131,Africa,50.728,12569.851770,Country: Botswana<br> Life Expectancy: 50.728<...,6.610603
203,Burkina Faso,2007,14326203,Africa,52.295,1217.032994,Country: Burkina Faso<br> Life Expectancy: 52....,19.543385

In [127]:
df_2007[df_2007['continent']=='Oceania']

,country,year,pop,continent,lifeExp,gdpPercap,text,size
71,Australia,2007,20434176,Oceania,81.235,34435.36744,Country: Australia<br> Life Expectancy: 81.235...,23.340643
1103,New Zealand,2007,4115771,Oceania,80.204,25185.00911,Country: New Zealand<br> Life Expectancy: 80.2...,10.475140

In [128]:
[60, 26.92763965464884]

[60, 26.92763965464884]

In [129]:
test_x = df_2007[df_2007['continent'] == 'Asia']['pop']
test_y = [9.330561207739747, 1.390827697025556, 20.266312242166443,
              6.211273648937339, 60, 4.3653750211924, 55.05795036085951,
              24.703896200017994, 13.769821732555231, 8.664520214956125,
              4.188652530719761, 18.654412200415056, 4.0651192623762835,
              7.975814912067495, 11.57117523159306, 3.271861016562374,
              8.231768913808876, 2.8011347940934943, 11.418845373343052,
              8.882667412223675, 2.9579312056937046, 21.49670117903256,
              15.768343552577761, 8.680479951148044, 3.525577657243318,
              7.4587209016354095, 7.261486641287726, 7.95397619750268,
              13.3280083790662, 15.256667990032932, 3.312103798885452,
              7.787039017632765]

test_tuple = zip(test_x,test_y)

In [130]:
test_tuple = sorted(test_tuple, key=lambda x: x[0])
test_x = [x[0] for x in test_tuple]
test_y = [y[1]**2 for y in test_tuple]

data=[go.Scatter(x=test_x, y=test_y)]
py.iplot(data)

In [131]:
africa_slope = 2.666051223553066e-05

In [132]:
test_y = [y[1] for y in test_tuple]

test_estimate = [math.sqrt(i*slope) for i in test_x]

In [133]:
import plotly.offline as py
import plotly.graph_objs as go
import math
py.init_notebook_mode()

test_trace = go.Scatter(x=test_x, y=test_y)
test_trace2 = go.Scatter(x=test_x, y= test_estimate)
data=[test_trace, test_trace2]
py.iplot(data)

In [134]:
test_y

[1.390827697025556,
 3.271861016562374,
 11.418845373343052,
 21.49670117903256,
 8.231768913808876,
 7.787039017632765,
 7.4587209016354095,
 4.0651192623762835,
 4.188652530719761,
 4.3653750211924,
 6.211273648937339,
 7.95397619750268,
 7.261486641287726,
 13.3280083790662,
 7.975814912067495,
 2.8011347940934943,
 8.664520214956125,
 3.525577657243318,
 2.9579312056937046,
 9.330561207739747,
 8.882667412223675,
 11.57117523159306,
 15.256667990032932,
 13.769821732555231,
 3.312103798885452,
 8.680479951148044,
 18.654412200415056,
 20.266312242166443,
 15.768343552577761,
 24.703896200017994,
 55.05795036085951,
 60]

In [135]:
test_estimate

[1.3908276970255558,
 2.6153712644332385,
 2.8011347940934934,
 2.9579312056937037,
 3.2718610165623736,
 3.3121037988854516,
 3.5255776572433173,
 4.065119262376282,
 4.188652530719759,
 4.365375021192399,
 6.211273648937337,
 7.261486641287724,
 7.458720901635408,
 7.953976197502679,
 7.975814912067494,
 8.231768913808875,
 8.664520214956124,
 8.680479951148044,
 8.882667412223674,
 9.330561207739745,
 11.41884537334305,
 11.571175231593056,
 13.328008379066198,
 13.769821732555227,
 15.256667990032929,
 15.768343552577758,
 18.65441220041505,
 20.26631224216644,
 21.496701179032556,
 24.703896200017986,
 55.05795036085949,
 59.999999999999986]

In [136]:
import plotly.plotly as py
import plotly.graph_objs as go

trace0 = go.Scatter(
    x=df_2007['gdpPercap'][df_2007['continent'] == 'Africa'],
    y=df_2007['lifeExp'][df_2007['continent'] == 'Africa'],
    mode='markers',
    name='Africa',
    text=df_2007['text'][df_2007['continent'] == 'Africa'],
    marker=dict(
        symbol='circle',
        sizemode='diameter',
        sizeref=0.85,
        size=df_2007['size'][df_2007['continent'] == 'Africa'],
        line=dict(
            width=2
        ),
    )
)
trace1 = go.Scatter(
    x=df_2007['gdpPercap'][df_2007['continent'] == 'Americas'],
    y=df_2007['lifeExp'][df_2007['continent'] == 'Americas'],
    mode='markers',
    name='Americas',
    text=df_2007['text'][df_2007['continent'] == 'Americas'],
    marker=dict(
        sizemode='diameter',
        sizeref=0.85,
        size=df_2007['size'][df_2007['continent'] == 'Americas'],
        line=dict(
            width=2
        ),
    )
)
trace2 = go.Scatter(
    x=df_2007['gdpPercap'][df_2007['continent'] == 'Asia'],
    y=df_2007['lifeExp'][df_2007['continent'] == 'Asia'],
    mode='markers',
    name='Asia',
    text=df_2007['text'][df_2007['continent'] == 'Asia'],
    marker=dict(
        sizemode='diameter',
        sizeref=0.85,
        size=df_2007['size'][df_2007['continent'] == 'Asia'],
        line=dict(
            width=2
        ),
    )
)
trace3 = go.Scatter(
    x=df_2007['gdpPercap'][df_2007['continent'] == 'Europe'],
    y=df_2007['lifeExp'][df_2007['continent'] == 'Europe'],
    mode='markers',
    name='Europe',
    text=df_2007['text'][df_2007['continent'] == 'Europe'],
    marker=dict(
        sizemode='diameter',
        sizeref=0.85,
        size=df_2007['size'][df_2007['continent'] == 'Europe'],
        line=dict(
            width=2
        ),
    )
)
trace4 = go.Scatter(
    x=df_2007['gdpPercap'][df_2007['continent'] == 'Oceania'],
    y=df_2007['lifeExp'][df_2007['continent'] == 'Oceania'],
    mode='markers',
    name='Oceania',
    text=df_2007['text'][df_2007['continent'] == 'Oceania'],
    marker=dict(
        sizemode='diameter',
        sizeref=0.85,
        size=df_2007['size'][df_2007['continent'] == 'Oceania'],
        line=dict(
            width=2
        ),
    )
)
data = [trace0, trace1, trace2, trace3, trace4]
layout = go.Layout(
    title='Life Expectancy v. Per Capita GDP, 2007',
    xaxis=dict(
        title='GDP per capita (2000 dollars)',
        gridcolor='rgb(255, 255, 255)',
        range=[2.003297660701705, 5.191505530708712],
        type='log',
        zerolinewidth=1,
        ticklen=5,
        gridwidth=2,
    ),
    yaxis=dict(
        title='Life Expectancy (years)',
        gridcolor='rgb(255, 255, 255)',
        range=[36.12621671352166, 91.72921793264332],
        zerolinewidth=1,
        ticklen=5,
        gridwidth=2,
    ),
    paper_bgcolor='rgb(243, 243, 243)',
    plot_bgcolor='rgb(243, 243, 243)',
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='life-expectancy-per-GDP-2007')

In [140]:
df_2007.sort(['pop'], ascending=False)

,country,year,pop,continent,lifeExp,gdpPercap,text,size
299,China,2007,1318683096,Asia,72.961,4959.114854,Country: China<br> Life Expectancy: 72.961<br>...,187.501378
707,India,2007,1110396331,Asia,64.698,2452.210407,Country: India<br> Life Expectancy: 64.698<br>...,172.057360
1619,United States,2007,301139947,Americas,78.242,42951.653090,Country: United States<br> Life Expectancy: 78...,89.602150
719,Indonesia,2007,223547000,Asia,70.650,3540.651564,Country: Indonesia<br> Life Expectancy: 70.65<...,77.200243
179,Brazil,2007,190010647,Americas,72.390,9065.800825,Country: Brazil<br> Life Expectancy: 72.39<br>...,71.174301
1175,Pakistan,2007,169270617,Asia,65.483,2605.947580,Country: Pakistan<br> Life Expectancy: 65.483<...,67.177685
107,Bangladesh,2007,150448339,Asia,64.062,1391.253792,Country: Bangladesh<br> Life Expectancy: 64.06...,63.332691
1139,Nigeria,2007,135031164,Africa,46.859,2013.977305,Country: Nigeria<br> Life Expectancy: 46.859<b...,60.000000
803,Japan,2007,127467972,Asia,82.603,31656.068060,Country: Japan<br> Life Expectancy: 82.603<br>...,58.295467
995,Mexico,2007,108700891,Americas,76.195,11977.574960,Country: Mexico<br> Life Expectancy: 76.195<br...,53.833274
1223,Philippines,2007,91077287,Asia,71.688,3190.481016,Country: Philippines<br> Life Expectancy: 71.6...,49.276436
1655,Vietnam,2007,85262356,Asia,74.249,2441.576404,Country: Vietnam<br> Life Expectancy: 74.249<b...,47.677438
575,Germany,2007,82400996,Europe,79.406,32170.374420,Country: Germany<br> Life Expectancy: 79.406<b...,46.870596
467,Egypt,2007,80264543,Africa,71.338,5581.180998,Country: Egypt<br> Life Expectancy: 71.338<br>...,46.258986
515,Ethiopia,2007,76511887,Africa,52.947,690.805576,Country: Ethiopia<br> Life Expectancy: 52.947<...,45.164655
1583,Turkey,2007,71158647,Europe,71.777,8458.276384,Country: Turkey<br> Life Expectancy: 71.777<br...,43.556010
731,Iran,2007,69453570,Asia,70.964,11605.714490,Country: Iran<br> Life Expectancy: 70.964<br>G...,43.031009
1535,Thailand,2007,65068149,Asia,70.616,7458.396327,Country: Thailand<br> Life Expectancy: 70.616<...,41.650332
335,"Congo, Dem. Rep.",2007,64606759,Africa,46.462,277.551859,"Country: Congo, Dem. Rep.<br> Life Expectancy:...",41.502401
539,France,2007,61083916,Europe,80.657,30470.016700,Country: France<br> Life Expectancy: 80.657<br...,40.355031
1607,United Kingdom,2007,60776238,Europe,79.425,33203.261280,Country: United Kingdom<br> Life Expectancy: 7...,40.253269
779,Italy,2007,58147733,Europe,80.546,28569.719700,Country: Italy<br> Life Expectancy: 80.546<br>...,39.373193
851,"Korea, Rep.",2007,49044790,Asia,78.623,23348.139730,"Country: Korea, Rep.<br> Life Expectancy: 78.6...",36.160188
1055,Myanmar,2007,47761980,Asia,62.069,944.000000,Country: Myanmar<br> Life Expectancy: 62.069<b...,35.684154
311,Colombia,2007,44227550,Americas,72.889,7006.580419,Country: Colombia<br> Life Expectancy: 72.889<...,34.338450
1415,South Africa,2007,43997828,Africa,49.339,9269.657808,Country: South Africa<br> Life Expectancy: 49....,34.249155
1451,Sudan,2007,42292929,Africa,58.556,2602.394995,Country: Sudan<br> Life Expectancy: 58.556<br>...,33.579028
1427,Spain,2007,40448191,Europe,80.941,28821.063700,Country: Spain<br> Life Expectancy: 80.941<br>...,32.838537
59,Argentina,2007,40301927,Americas,75.320,12779.379640,Country: Argentina<br> Life Expectancy: 75.32<...,32.779109
1235,Poland,2007,38518241,Europe,75.563,15389.924680,Country: Poland<br> Life Expectancy: 75.563<br...,32.045531
...,...,...,...,...,...,...,...,...
1259,Puerto Rico,2007,3942491,Americas,78.746,19328.709010,Country: Puerto Rico<br> Life Expectancy: 78.7...,10.252260
875,Lebanon,2007,3921278,Asia,71.993,10461.058680,Country: Lebanon<br> Life Expectancy: 71.993<b...,10.224641
347,"Congo, Rep.",2007,3800610,Africa,55.322,3632.557798,"Country: Congo, Rep.<br> Life Expectancy: 55.3...",10.066092
23,Albania,2007,3600523,Europe,76.423,5937.029526,Country: Albania<br> Life Expectancy: 76.423<b...,9.797540
1631,Uruguay,2007,3447496,Americas,76.384,10611.462990,Country: Uruguay<br> Life Expectancy: 76.384<b...,9.587075
971,Mauritania,2007,3270065,Africa,64.164,1803.151496,Country: Mauritania<br> Life Expectancy: 64.16...,9.337109
1187,Panama,2007,3242173,Americas,75.537,9809.185636,Country: Panama<br> Life Expectancy: 75.537<br...,9.297204
1163,Oman,2007,3204897,Asia,75.640,22316.192870,Country: Oman<br> Life Expectancy: 75.64<br>GD...,9.243603
899,Liberia,2007,3193942,Africa,45.678,414.507341,Country: Liberia<br> Life Expectancy: 45.678<b...,9.227791
1007,Mongolia,2007,2874127,Asia,66.803,3095.772271,Country: Mongolia<br> Life Expectancy: 66.803<...,8.753611
791,Jamaica,2007,2780132,Americas,72.567,7320.880262,Country: Jamaica<br> Life Expectancy: 72.567<b...,8.609282
863,Kuwait,2007,2505559,Asia,77.588,47306.989780,Country: Kuwait<br> Life Expectancy: 77.588<br...,8.173095
1067,Namibia,2007,2055080,Africa,52.906,4811.060429,Country: Namibia<br> Life Expectancy: 52.906<b...,7.401992
887,Lesotho,2007,2012649,Africa,42.592,1569.331442,Country: Lesotho<br> Life Expectancy: 42.592<b...,7.325179
1391,Slovenia,2007,2009245,Europe,77.926,25768.257590,Country: Slovenia<br> Life Expectancy: 77.926<...,7.318982
563,Gambia,2007,1688359,Africa,59.448,752.749726,Country: Gambia<br> Life Expectancy: 59.448<br...,6.709137
167,Botswana,2007,1639131,Africa,50.728,12569.851770,Country: Botswana<br> Life Expectancy: 50.728<...,6.610603
635,Guinea-Bissau,2007,1472041,Africa,46.388,579.231743,Country: Guinea-Bissau<br> Life Expectancy: 46...,6.264612
551,Gabon,2007,1454867,Africa,56.735,13206.484520,Country: Gabon<br> Life Expectancy: 56.735<br>...,6.227961
983,Mauritius,2007,1250882,Africa,72.801,10956.991120,Country: Mauritius<br> Life Expectancy: 72.801...,5.774873
1463,Swaziland,2007,1133066,Africa,39.613,4513.480643,Country: Swaziland<br> Life Expectancy: 39.613...,5.496191
1559,Trinidad and Tobago,2007,1056608,Americas,69.819,18008.509240,Country: Trinidad and Tobago<br> Life Expectan...,5.307515
1271,Reunion,2007,798094,Africa,76.442,7670.122558,Country: Reunion<br> Life Expectancy: 76.442<b...,4.612764
323,Comoros,2007,710960,Africa,65.152,986.147879,Country: Comoros<br> Life Expectancy: 65.152<b...,4.353683
95,Bahrain,2007,708573,Asia,75.635,29796.048340,Country: Bahrain<br> Life Expectancy: 75.635<b...,4.346368
1019,Montenegro,2007,684736,Europe,74.543,9253.896111,Country: Montenegro<br> Life Expectancy: 74.54...,4.272635
491,Equatorial Guinea,2007,551201,Africa,51.579,12154.089750,Country: Equatorial Guinea<br> Life Expectancy...,3.833445
431,Djibouti,2007,496374,Africa,54.791,2082.481567,Country: Djibouti<br> Life Expectancy: 54.791<...,3.637799
695,Iceland,2007,301931,Europe,81.757,36180.789190,Country: Iceland<br> Life Expectancy: 81.757<b...,2.837188
1307,Sao Tome and Principe,2007,199579,Africa,65.528,1598.435089,Country: Sao Tome and Principe<br> Life Expect...,2.306703